### ISSUE TITLE
Docs fail to build because readthedocs config is missing

### ISSUE THREAD

**Issue by cortadocodes** [octue/django-gcp#58]
### What is the current behavior?
The docs [fail to build](https://readthedocs.org/projects/django-gcp/builds/22926500/) as there is no readthedocs config file.

### What is the expected behavior?
The docs build.

**Comment by thclark** [comment]
Should contain somehting like:
```
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt
```
